import type { Student, Cohort, StudentGroup, Instructor, Assessment, AcademicYear } from "~/types"

// Mock data - will be replaced with API calls
export function useMockData() {
  const cohorts: Cohort[] = [
    {
      id: "c1",
      name: "A1",
      rotationGroupId: "rg1",
      academicYearId: "ay1",
      hospital: "San Fernando General Hospital",
      instructorId: "i1",
      studentIds: ["s1", "s2"],
    },
    {
      id: "c2",
      name: "A2",
      rotationGroupId: "rg1",
      academicYearId: "ay1",
      hospital: "Port of Spain General Hospital",
      instructorId: "i2",
      studentIds: [],
    },
    {
      id: "c3",
      name: "A3",
      rotationGroupId: "rg1",
      academicYearId: "ay1",
      hospital: "Mount Hope Women's Hospital",
      studentIds: [],
    },
    {
      id: "c4",
      name: "B1",
      rotationGroupId: "rg2",
      academicYearId: "ay1",
      hospital: "San Fernando General Hospital",
      instructorId: "i1",
      studentIds: ["s3", "s4"],
    },
    {
      id: "c5",
      name: "B2",
      rotationGroupId: "rg2",
      academicYearId: "ay1",
      hospital: "Sangre Grande Hospital",
      studentIds: [],
    },
    {
      id: "c6",
      name: "C1",
      rotationGroupId: "rg3",
      academicYearId: "ay1",
      hospital: "San Fernando General Hospital",
      instructorId: "i2",
      studentIds: ["s5", "s6"],
    },
  ]

  const students: Student[] = [
    {
      id: "s1",
      name: "Alex Johnson",
      email: "alex@university.edu",
      studentId: "STU001",
      academicYearId: "ay1",
      rotationGroupId: "rg1",
      cohortId: "c1",
    },
    {
      id: "s2",
      name: "Maria Garcia",
      email: "maria@university.edu",
      studentId: "STU002",
      academicYearId: "ay1",
      rotationGroupId: "rg1",
      cohortId: "c1",
    },
    {
      id: "s3",
      name: "James Chen",
      email: "james@university.edu",
      studentId: "STU003",
      academicYearId: "ay1",
      rotationGroupId: "rg2",
      cohortId: "c4",
    },
    {
      id: "s4",
      name: "Sarah Williams",
      email: "sarah@university.edu",
      studentId: "STU004",
      academicYearId: "ay1",
      rotationGroupId: "rg2",
      cohortId: "c4",
    },
    {
      id: "s5",
      name: "Michael Brown",
      email: "michael@university.edu",
      studentId: "STU005",
      academicYearId: "ay1",
      rotationGroupId: "rg3",
      cohortId: "c6",
    },
    {
      id: "s6",
      name: "Emily Davis",
      email: "emily@university.edu",
      studentId: "STU006",
      academicYearId: "ay1",
      rotationGroupId: "rg3",
      cohortId: "c6",
    },
    {
      id: "s7",
      name: "David Lee",
      email: "david@university.edu",
      studentId: "STU007",
      academicYearId: "ay1",
      rotationGroupId: "rg1",
    },
    {
      id: "s8",
      name: "Lisa Wang",
      email: "lisa@university.edu",
      studentId: "STU008",
      academicYearId: "ay1",
      rotationGroupId: "rg1",
    },
  ]

  const groups: StudentGroup[] = [
    { id: "g1", name: "Group Alpha", studentIds: ["s1", "s2", "s3", "s4"] },
    { id: "g2", name: "Group Beta", studentIds: ["s5", "s6"] },
  ]

  const instructors: Instructor[] = [
    {
      id: "i1",
      name: "Dr. Shane Khan",
      email: "tanqueray@university.edu",
      status: "active",
      assignedStudentIds: ["s1", "s2"],
      assignedGroupIds: ["g1"],
    },
    {
      id: "i2",
      name: "Prof. Zalim",
      email: "qa@university.edu",
      status: "active",
      assignedStudentIds: ["s3", "s4"],
      assignedGroupIds: [],
    },
    {
      id: "i3",
      name: "Dr. Shazzy",
      email: "shazman@university.edu",
      status: "inactive",
      assignedStudentIds: [],
      assignedGroupIds: [],
    },
  ]

  const assessments: Assessment[] = [
    {
      id: "a1",
      studentId: "s1",
      criterion1: 85,
      criterion2: 90,
      criterion3: 78,
      criterion4: 88,
      criterion5: 92,
      submittedBy: "i1",
      submittedAt: "2024-01-15",
    },
    {
      id: "a2",
      studentId: "s2",
      criterion1: 92,
      criterion2: 88,
      criterion3: 95,
      criterion4: 90,
      criterion5: 87,
      submittedBy: "i1",
      submittedAt: "2024-01-15",
    },
    {
      id: "a3",
      studentId: "s3",
      criterion1: 78,
      criterion2: 82,
      criterion3: 80,
      criterion4: 75,
      criterion5: 85,
      submittedBy: "i2",
      submittedAt: "2024-01-16",
    },
  ]

  const academicYears: AcademicYear[] = [
    {
      id: "ay1",
      name: "2024-2025",
      startDate: "2024-09-01",
      endDate: "2025-06-30",
      isActive: true,
      rotationGroups: [
        {
          id: "rg1",
          name: "A",
          startDate: "2025-01-14",
          endDate: "2025-02-27",
          cohortCount: 8,
          studentCount: 40,
          gradedCount: 35,
          status: "active",
        },
        {
          id: "rg2",
          name: "B",
          startDate: "2025-03-01",
          endDate: "2025-04-15",
          cohortCount: 8,
          studentCount: 40,
          gradedCount: 40,
          status: "complete",
        },
        {
          id: "rg3",
          name: "C",
          startDate: "2025-04-16",
          endDate: "2025-05-31",
          cohortCount: 8,
          studentCount: 38,
          gradedCount: 0,
          status: "pending",
        },
        {
          id: "rg4",
          name: "D",
          startDate: "2024-09-15",
          endDate: "2024-10-31",
          cohortCount: 8,
          studentCount: 42,
          gradedCount: 42,
          status: "complete",
        },
        {
          id: "rg5",
          name: "E",
          startDate: "2024-11-01",
          endDate: "2024-12-15",
          cohortCount: 8,
          studentCount: 40,
          gradedCount: 40,
          status: "complete",
        },
        {
          id: "rg6",
          name: "F",
          startDate: "2024-12-16",
          endDate: "2025-01-13",
          cohortCount: 8,
          studentCount: 39,
          gradedCount: 39,
          status: "complete",
        },
      ],
    },
    {
      id: "ay2",
      name: "2023-2024",
      startDate: "2023-09-01",
      endDate: "2024-06-30",
      isActive: false,
      rotationGroups: [
        {
          id: "rg7",
          name: "A",
          startDate: "2024-01-15",
          endDate: "2024-02-28",
          cohortCount: 8,
          studentCount: 38,
          gradedCount: 38,
          status: "complete",
        },
        {
          id: "rg8",
          name: "B",
          startDate: "2024-03-01",
          endDate: "2024-04-15",
          cohortCount: 8,
          studentCount: 40,
          gradedCount: 40,
          status: "complete",
        },
        {
          id: "rg9",
          name: "C",
          startDate: "2024-04-16",
          endDate: "2024-05-31",
          cohortCount: 8,
          studentCount: 36,
          gradedCount: 36,
          status: "complete",
        },
        {
          id: "rg10",
          name: "D",
          startDate: "2023-09-15",
          endDate: "2023-10-31",
          cohortCount: 8,
          studentCount: 42,
          gradedCount: 42,
          status: "complete",
        },
        {
          id: "rg11",
          name: "E",
          startDate: "2023-11-01",
          endDate: "2023-12-15",
          cohortCount: 8,
          studentCount: 40,
          gradedCount: 40,
          status: "complete",
        },
        {
          id: "rg12",
          name: "F",
          startDate: "2023-12-16",
          endDate: "2024-01-14",
          cohortCount: 8,
          studentCount: 39,
          gradedCount: 39,
          status: "complete",
        },
      ],
    },
  ]

  return {
    students,
    cohorts,
    groups,
    instructors,
    assessments,
    academicYears,
  }
}
